---

- name: Check where bash is installed
  command: which bash
  register: vault_check_bash_path
  failed_when: false
  changed_when: false

- name: Check that unzip is installed
  command: which unzip
  register: vault_check_unzip_installed
  failed_when: false
  changed_when: false

- name: Fail play if unzip is not installed
  fail:
    msg: unzip was not found and is required for unpacking vault, please ensure this is installed.
  when: vault_check_unzip_installed.rc > 0
        and not vault_install_os_dependencies

- name: Check for existing vault binary
  stat:
    path: "{{ vault_install_dir }}/vault"
  register: vault_check_existing

- name: Check vault binary version if binary already exists
  shell: |
    set -o pipefail
    {{ vault_install_dir }}/vault version | awk '{ print $NF }' | sed 's/^v//'
  args:
    executable: "{{ vault_check_bash_path.stdout_lines[0] }}"
  changed_when: false
  register: vault_check_existing_version
  when: vault_check_existing.stat.exists