---

- name: Ensure unzip is installed (YUM)
  yum:
    name: unzip
    state: present
  when: ansible_pkg_mgr == "yum"

- name: Ensure unzip is installed (DNF)
  dnf:
    name: unzip
    state: present
  when: ansible_pkg_mgr == "dnf"